# SPDX-License-Identifier: AGPL-3.0-or-later
# FR-080-AC-2 / TC-205: `cargo deny check bans` denies `inventory`, `linkme`
# and `ctor` outright. ADR-012 §5.3's registry evidence: the `#185` registry
# (`src/route.rs`) is an ordinary value, never populated through a
# link-time/plugin-discovery mechanism, and this is the positive-fail gate
# that would catch a future contributor reintroducing one -- it is not
# satisfied merely by the crate graph's current absence of the three crates.
#
# Scoped to `check bans` only (`make cargo-deny-bans`, `cargo deny check
# bans`): this file configures no license or advisory policy, so it does not
# claim to gate either, and a bare `cargo deny check` should not be run
# against it for that reason.
[graph]
all-features = true

[bans]
multiple-versions = "allow"
wildcards = "allow"
deny = [
    { name = "inventory" },
    { name = "linkme" },
    { name = "ctor" },
]
