// SPDX-License-Identifier: AGPL-3.0-or-later
//! ADR-011 §7.2 (QSL-181 AC-3, QSL-182 AC-3): the root crate re-exports no
//! item of an extracted layer crate. Callers name each item at its layer
//! crate's own path (`qsl_package::CheckedPackage`,
//! `qsl_semantics::check::CheckedExpression`), so this crate's public
//! surface never becomes a second path to a moved item.
//!
//! The layer crates are read from `cargo metadata`: every workspace crate
//! the root crate names in `[dependencies]` (a `path` dependency), by its
//! Rust name. A crate extracted later is covered as soon as the root crate
//! depends on it.
//!
//! The scan parses every `.rs` file under `src/` with `syn`, not text,
//! because the forms it must see are structural: a `use` tree's root after
//! a rename, a crate alias bound in one item and used in another, and the
//! paths inside a type alias's type. It fails on three public shapes:
//!
//! - `pub use` whose root is a layer crate or a *layer name*;
//! - `pub type` whose type names a path rooted at a layer crate or a layer
//!   name;
//! - `pub extern crate` of a layer crate.
//!
//! A *layer name* is any name a `use` or `extern crate` item of the root
//! crate binds from a layer crate, at any visibility and in any file:
//! `use qsl_package as layer_four;` binds `layer_four`, and `use
//! qsl_package::CheckedPackage;` binds `CheckedPackage`, so `pub use
//! layer_four::CheckedPackage;` and `pub type Alias = CheckedPackage;` both
//! fail. The set is crate-wide rather than per file, so a `pub type` naming a
//! `pub(crate)` import from another module is caught too; the cost is that a
//! local type sharing a name with a layer import would be flagged, which
//! the real tree does not do today. Only `pub` counts: `pub(crate)` and
//! `pub(super)` items are imports inside this crate, not its public surface.
//! Items generated by a macro are not seen; the root crate defines no
//! macro that emits a `use`, `type` or `extern crate` item.
use std::collections::BTreeSet;
use std::path::{Path, PathBuf};

use ix_trace_rs::trace;
use syn::visit::Visit;

fn root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).to_path_buf()
}

/// Rust names of the workspace crates the root crate depends on.
fn layer_crates() -> BTreeSet<String> {
    let cargo = std::env::var("CARGO").unwrap_or_else(|_| "cargo".to_owned());
    let output = std::process::Command::new(cargo)
        .current_dir(root())
        .args([
            "metadata",
            "--format-version",
            "1",
            "--no-deps",
            "--offline",
        ])
        .output()
        .expect("cargo metadata runs");
    assert!(
        output.status.success(),
        "cargo metadata failed: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    let metadata: serde_json::Value =
        serde_json::from_slice(&output.stdout).expect("cargo metadata emits JSON");
    let package = metadata["packages"]
        .as_array()
        .expect("cargo metadata lists packages")
        .iter()
        .find(|package| package["name"] == "quire-spec-language")
        .expect("the root package is listed");
    package["dependencies"]
        .as_array()
        .expect("a dependency list")
        .iter()
        .filter(|dependency| dependency["kind"].is_null() && dependency["path"].is_string())
        .map(|dependency| {
            dependency["rename"]
                .as_str()
                .or_else(|| dependency["name"].as_str())
                .expect("a dependency name")
                .replace('-', "_")
        })
        .collect()
}

/// One use-tree leaf: the path's first segment and the name the leaf binds
/// (`None` for a glob).
fn leaves(tree: &syn::UseTree, first: Option<&str>, out: &mut Vec<(String, Option<String>)>) {
    let root_or = |ident: &syn::Ident| first.map_or_else(|| ident.to_string(), str::to_owned);
    match tree {
        syn::UseTree::Path(path) => leaves(&path.tree, Some(&root_or(&path.ident)), out),
        syn::UseTree::Name(name) => {
            let bound = name.ident.to_string();
            let bound = if bound == "self" {
                first.map(str::to_owned)
            } else {
                Some(bound)
            };
            out.push((root_or(&name.ident), bound));
        }
        syn::UseTree::Rename(rename) => {
            out.push((root_or(&rename.ident), Some(rename.rename.to_string())));
        }
        syn::UseTree::Glob(_) => {
            if let Some(first) = first {
                out.push((first.to_owned(), None));
            }
        }
        syn::UseTree::Group(group) => {
            for item in &group.items {
                leaves(item, first, out);
            }
        }
    }
}

/// Every item of a file, inline modules included.
fn all_items(items: &[syn::Item], out: &mut Vec<syn::Item>) {
    for item in items {
        if let syn::Item::Mod(module) = item {
            if let Some((_, nested)) = &module.content {
                all_items(nested, out);
            }
        }
        out.push(item.clone());
    }
}

/// The names bound from a layer crate by any `use` or `extern crate` item.
/// Iterates to a fixed point, so `use qsl_package as a; use a::X;` binds
/// both `a` and `X`.
fn layer_names(items: &[syn::Item], layers: &BTreeSet<String>) -> BTreeSet<String> {
    let mut names = layers.clone();
    loop {
        let before = names.len();
        for item in items {
            match item {
                syn::Item::Use(item_use) => {
                    let mut found = Vec::new();
                    leaves(&item_use.tree, None, &mut found);
                    for (first, bound) in found {
                        if names.contains(&first) {
                            names.extend(bound);
                        }
                    }
                }
                syn::Item::ExternCrate(extern_crate)
                    if layers.contains(&extern_crate.ident.to_string()) =>
                {
                    if let Some((_, rename)) = &extern_crate.rename {
                        names.insert(rename.to_string());
                    }
                }
                _ => {}
            }
        }
        if names.len() == before {
            return names;
        }
    }
}

/// The first segment of every path named in a type, at any depth.
struct TypePaths(BTreeSet<String>);

impl<'ast> Visit<'ast> for TypePaths {
    fn visit_path(&mut self, path: &'ast syn::Path) {
        if let Some(first) = path.segments.first() {
            self.0.insert(first.ident.to_string());
        }
        syn::visit::visit_path(self, path);
    }
}

/// Each public item among `items` that exposes a layer-crate item, as
/// `(kind, name)`.
fn exposures(
    items: &[syn::Item],
    layers: &BTreeSet<String>,
    names: &BTreeSet<String>,
) -> Vec<(&'static str, String)> {
    let mut found = Vec::new();
    for item in items {
        match item {
            syn::Item::Use(item_use) if matches!(item_use.vis, syn::Visibility::Public(_)) => {
                let mut leaves_found = Vec::new();
                leaves(&item_use.tree, None, &mut leaves_found);
                for (first, bound) in leaves_found {
                    if names.contains(&first) {
                        found.push(("pub use", bound.unwrap_or_else(|| format!("{first}::*"))));
                    }
                }
            }
            syn::Item::Type(item_type) if matches!(item_type.vis, syn::Visibility::Public(_)) => {
                let mut paths = TypePaths(BTreeSet::new());
                paths.visit_type(&item_type.ty);
                if paths.0.iter().any(|first| names.contains(first)) {
                    found.push(("pub type", item_type.ident.to_string()));
                }
            }
            syn::Item::ExternCrate(extern_crate)
                if matches!(extern_crate.vis, syn::Visibility::Public(_))
                    && layers.contains(&extern_crate.ident.to_string()) =>
            {
                found.push(("pub extern crate", extern_crate.ident.to_string()));
            }
            _ => {}
        }
    }
    found
}

fn parse_items(sources: &[(String, String)]) -> Vec<(String, Vec<syn::Item>)> {
    sources
        .iter()
        .map(|(file, source)| {
            let parsed = syn::parse_file(source).unwrap_or_else(|error| panic!("{file}: {error}"));
            let mut items = Vec::new();
            all_items(&parsed.items, &mut items);
            (file.clone(), items)
        })
        .collect()
}

/// Every exposure across `sources`, as `(file, kind, name)`.
fn scan(
    sources: &[(String, String)],
    layers: &BTreeSet<String>,
) -> Vec<(String, &'static str, String)> {
    let files = parse_items(sources);
    let every_item: Vec<syn::Item> = files.iter().flat_map(|(_, items)| items.clone()).collect();
    let names = layer_names(&every_item, layers);
    files
        .iter()
        .flat_map(|(file, items)| {
            exposures(items, layers, &names)
                .into_iter()
                .map(move |(kind, name)| (file.clone(), kind, name))
        })
        .collect()
}

fn root_sources() -> Vec<(String, String)> {
    fn walk(dir: &Path, out: &mut Vec<PathBuf>) {
        for entry in std::fs::read_dir(dir).expect("the source tree lists") {
            let path = entry.expect("a directory entry").path();
            if path.is_dir() {
                walk(&path, out);
            } else if path.extension().is_some_and(|extension| extension == "rs") {
                out.push(path);
            }
        }
    }
    let src = root().join("src");
    let mut files = Vec::new();
    walk(&src, &mut files);
    files.sort();
    files
        .into_iter()
        .map(|path| {
            let relative = path
                .strip_prefix(&src)
                .expect("under src")
                .to_string_lossy()
                .replace('\\', "/");
            (
                relative,
                std::fs::read_to_string(&path).expect("a source file reads"),
            )
        })
        .collect()
}

/// TC-256 step 3 and TC-172 step 6 as amended by QSL-182 and QSL-181:
/// `value::expression` re-exports neither `CheckedPackage` nor any `check`
/// item, and no other public item of the root crate exposes a layer
/// crate's item.
#[trace("FR-087-AC-9", "TC-256", "TC-172")]
#[test]
fn the_root_crate_reexports_no_layer_crate_item() {
    let layers = layer_crates();
    for expected in [
        "quire_exact",
        "qsl_foundation",
        "qsl_semantics",
        "qsl_package",
    ] {
        assert!(
            layers.contains(expected),
            "{expected} missing from {layers:?}"
        );
    }
    let found = scan(&root_sources(), &layers);
    assert!(
        found.is_empty(),
        "root-crate items exposing layer-crate items: {found:?}"
    );
}

/// The scanner against each shape it must catch and each it must pass.
#[trace("FR-087-AC-9", "TC-256", "TC-172")]
#[test]
fn the_reexport_scan_catches_every_public_shape() {
    let layers: BTreeSet<String> = ["qsl_package", "qsl_semantics"]
        .into_iter()
        .map(str::to_owned)
        .collect();
    let sources = [
        (
            "a.rs",
            "use qsl_package::CheckedPackage;\n\
             pub use qsl_package::CheckedPackage as Direct;\n\
             pub use ::qsl_semantics::{check::CheckedExpression, library};\n\
             pub(crate) use qsl_package::EmittedPackage;\n\
             mod inner { pub use qsl_package::*; }\n\
             pub use serde_json::Value;\n\
             pub type Local = Vec<usize>;\n",
        ),
        (
            "b.rs",
            "use qsl_package as layer_four;\n\
             pub use layer_four::CheckedPackage as ViaAlias;\n\
             pub type Emitted = qsl_package::EmittedPackage;\n\
             pub type Wrapped = Option<layer_four::CheckedPackage>;\n\
             pub type ViaImport = EmittedPackage;\n\
             pub extern crate qsl_package;\n\
             extern crate qsl_semantics as three;\n\
             pub use three::check;\n",
        ),
    ]
    .map(|(file, source)| (file.to_owned(), source.to_owned()));
    let found: Vec<(String, &str, String)> = scan(&sources, &layers);
    let summary: Vec<(&str, &str, &str)> = found
        .iter()
        .map(|(file, kind, name)| (file.as_str(), *kind, name.as_str()))
        .collect();
    assert_eq!(
        summary,
        [
            ("a.rs", "pub use", "Direct"),
            ("a.rs", "pub use", "CheckedExpression"),
            ("a.rs", "pub use", "library"),
            ("a.rs", "pub use", "qsl_package::*"),
            ("b.rs", "pub use", "ViaAlias"),
            ("b.rs", "pub type", "Emitted"),
            ("b.rs", "pub type", "Wrapped"),
            ("b.rs", "pub type", "ViaImport"),
            ("b.rs", "pub extern crate", "qsl_package"),
            ("b.rs", "pub use", "check"),
        ]
    );
}
