// SPDX-License-Identifier: AGPL-3.0-or-later
//! FR-061 (ADR-011 §7.1: "QSL's own Cargo.lock resolves exactly one revision
//! per quire-ecosystem crate"): the duplicate-revision check.
//!
//! Reads `Cargo.lock` as plain text. `Cargo.lock` is a stable, Cargo-owned
//! format (`[[package]]` stanzas of `key = "value"` lines); this parser reads
//! only the three fields this check needs (`name`, `version`, `source`) and
//! is not a general TOML reader.

use std::path::Path;

use crate::error::{Code, Error, Result};

#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub(crate) struct LockedPackage {
    pub(crate) name: String,
    pub(crate) version: String,
    pub(crate) source: Option<String>,
}

/// Parse every `[[package]]` stanza's `name`, `version` and `source`.
pub(crate) fn parse_lockfile(text: &str) -> Vec<LockedPackage> {
    let mut packages = Vec::new();
    let mut current: Option<LockedPackage> = None;
    for line in text.lines() {
        let line = line.trim();
        if line == "[[package]]" {
            if let Some(package) = current.take() {
                packages.push(package);
            }
            current = Some(LockedPackage::default());
            continue;
        }
        let Some(package) = current.as_mut() else {
            continue;
        };
        if let Some(value) = field_value(line, "name") {
            package.name = value;
        } else if let Some(value) = field_value(line, "version") {
            package.version = value;
        } else if let Some(value) = field_value(line, "source") {
            package.source = Some(value);
        }
    }
    if let Some(package) = current.take() {
        packages.push(package);
    }
    packages
}

fn field_value(line: &str, key: &str) -> Option<String> {
    let rest = line.strip_prefix(key)?;
    let rest = rest.trim_start();
    let rest = rest.strip_prefix('=')?;
    let rest = rest.trim();
    let rest = rest.strip_prefix('"')?;
    let end = rest.find('"')?;
    Some(rest[..end].to_owned())
}

pub(crate) fn read_lockfile(path: &Path) -> Result<Vec<LockedPackage>> {
    let text = std::fs::read_to_string(path).map_err(|error| Error::io(path, error))?;
    let packages = parse_lockfile(&text);
    if packages.is_empty() {
        return Err(Error::new(Code::InvalidLockfile, "no [[package]] stanza found").at(path));
    }
    Ok(packages)
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub(crate) struct DuplicateRevision {
    pub(crate) name: String,
    pub(crate) sources: Vec<Option<String>>,
}

/// A quire-ecosystem crate: named `quire-*`, or the one QSL package alias
/// (`quire-contract-model`, the crate name IR's workspace member publishes
/// under, consumed as `quire-contract-ir` in this repo's own `Cargo.toml`).
fn is_ecosystem_crate(name: &str) -> bool {
    name.starts_with("quire-") || name == "quire_contract_model"
}

/// ADR-011 §7.1: exactly one revision (source string) per ecosystem crate
/// name. Two `[[package]]` stanzas with the same name and different sources
/// mean the lock resolved two different git revisions (or a mix of a git
/// revision and a registry release) of what is meant to be one dependency.
pub(crate) fn check(packages: &[LockedPackage]) -> Vec<DuplicateRevision> {
    let mut by_name: Vec<(&str, Vec<Option<String>>)> = Vec::new();
    for package in packages
        .iter()
        .filter(|package| is_ecosystem_crate(&package.name))
    {
        match by_name.iter_mut().find(|(name, _)| *name == package.name) {
            Some((_, sources)) => sources.push(package.source.clone()),
            None => by_name.push((package.name.as_str(), vec![package.source.clone()])),
        }
    }
    by_name
        .into_iter()
        .filter(|(_, sources)| {
            let mut distinct = sources.clone();
            distinct.sort();
            distinct.dedup();
            distinct.len() > 1
        })
        .map(|(name, sources)| DuplicateRevision {
            name: name.to_owned(),
            sources,
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    const LOCKFILE_ONE_REVISION_EACH: &str = r#"
# This file is automatically @generated by Cargo.
version = 3

[[package]]
name = "quire-contract-ir"
version = "0.1.0"
source = "git+https://github.com/agent-ix/quire-contract-ir?rev=53cc03c#53cc03c"

[[package]]
name = "serde"
version = "1.0.228"
source = "registry+https://github.com/rust-lang/crates.io-index"
"#;

    const LOCKFILE_DUPLICATE_REVISION: &str = r#"
[[package]]
name = "quire-contract-ir"
version = "0.1.0"
source = "git+https://github.com/agent-ix/quire-contract-ir?rev=53cc03c#53cc03c"

[[package]]
name = "quire-contract-ir"
version = "0.1.0"
source = "git+https://github.com/agent-ix/quire-contract-ir?rev=04eb6f8#04eb6f8"
"#;

    /// tc_arch_lint_duplicate_revisions_001: parsing recovers name, version
    /// and source per stanza.
    #[test]
    fn tc_arch_lint_duplicate_revisions_001_parses_stanzas() {
        let packages = parse_lockfile(LOCKFILE_ONE_REVISION_EACH);
        assert_eq!(packages.len(), 2);
        assert_eq!(packages[0].name, "quire-contract-ir");
        assert_eq!(packages[0].version, "0.1.0");
        assert!(packages[0].source.as_deref().unwrap().contains("53cc03c"));
    }

    /// tc_arch_lint_duplicate_revisions_002: one revision per ecosystem
    /// crate reports no duplicate; a non-ecosystem crate (`serde`) is
    /// ignored even though it also resolves to one entry.
    #[test]
    fn tc_arch_lint_duplicate_revisions_002_one_revision_each_is_clean() {
        let packages = parse_lockfile(LOCKFILE_ONE_REVISION_EACH);
        assert!(check(&packages).is_empty());
    }

    /// tc_arch_lint_duplicate_revisions_003 (negative control): the same
    /// crate name resolved to two different git revisions is reported.
    #[test]
    fn tc_arch_lint_duplicate_revisions_003_two_revisions_is_a_violation() {
        let packages = parse_lockfile(LOCKFILE_DUPLICATE_REVISION);
        let duplicates = check(&packages);
        assert_eq!(duplicates.len(), 1);
        assert_eq!(duplicates[0].name, "quire-contract-ir");
        assert_eq!(duplicates[0].sources.len(), 2);
    }

    /// tc_arch_lint_duplicate_revisions_004: a crate name outside the
    /// `quire-` ecosystem is never reported, even with two distinct sources
    /// (for example two vendored copies of an unrelated crate at different
    /// versions is ordinary and out of this check's scope).
    #[test]
    fn tc_arch_lint_duplicate_revisions_004_non_ecosystem_crate_is_ignored() {
        let lockfile = r#"
[[package]]
name = "serde"
version = "1.0.228"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "serde"
version = "1.0.100"
source = "registry+https://github.com/rust-lang/crates.io-index"
"#;
        let packages = parse_lockfile(lockfile);
        assert!(check(&packages).is_empty());
    }
}
